# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a75197f851536ff6b2ad25b2fff952ac"
name = "test-market-app"
handle = "test-market-app-2"
application_url = "https://conclude-vulnerable-authorization-pgp.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-640d3b65.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_analytics,read_assigned_fulfillment_orders,read_content,read_content_entries,read_content_models,read_customers,read_discounts,read_draft_orders,read_files,read_fulfillments,read_gift_cards,read_inventory,read_legal_policies,read_locales,read_locations,read_marketing_events,read_markets,read_merchant_managed_fulfillment_orders,read_metaobject_definitions,read_metaobjects,read_orders,read_payment_terms,read_price_rules,read_product_feeds,read_product_listings,read_products,read_publications,read_purchase_options,read_reports,read_resource_feedbacks,read_script_tags,read_shipping,read_shopify_payments_accounts,read_shopify_payments_bank_accounts,read_shopify_payments_disputes,read_shopify_payments_payouts,read_themes,read_third_party_fulfillment_orders,read_translations,write_assigned_fulfillment_orders,write_content,write_content_entries,write_content_models,write_customers,write_discounts,write_draft_orders,write_files,write_fulfillments,write_gift_cards,write_inventory,write_locales,write_marketing_events,write_markets,write_merchant_managed_fulfillment_orders,write_metaobject_definitions,write_metaobjects,write_orders,write_payment_terms,write_price_rules,write_product_feeds,write_products,write_publications,write_purchase_options,write_reports,write_resource_feedbacks,write_script_tags,write_shipping,write_themes,write_third_party_fulfillment_orders,write_translations"

[auth]
redirect_urls = [
  "https://conclude-vulnerable-authorization-pgp.trycloudflare.com/auth/callback",
  "https://conclude-vulnerable-authorization-pgp.trycloudflare.com/auth/shopify/callback",
  "https://conclude-vulnerable-authorization-pgp.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
